# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-02-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date_published')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Company')),
            ],
            options={
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': 'pub_date',
                'verbose_name': 'investment thesis',
            },
        ),
    ]
